### ISSUE TITLE
When  ./run-emulator-test.sh  in deca/scripts, error。

### ISSUE THREAD

**Issue by Crosshairs** [rhit-neuro/deca#2]
![捕获1](https://user-images.githubusercontent.com/43806118/68572057-735ce380-049f-11ea-987a-f169bb865d3b.PNG)

**Comment by heidecjj** [comment]
Are you using the `rhitdeca/rocket-chip-env` docker image to run `run-emulator-test.sh`?

**Comment by Crosshairs** [comment]
No.Because when I use docker，I will find some internet problem.

**Comment by Crosshairs** [comment]
So.I don't use the docker

**Comment by Crosshairs** [comment]
Now,I use the docker.But error.
![image](https://user-images.githubusercontent.com/43806118/68673127-fceadf00-058d-11ea-95dc-e0b75de19430.png)

**Comment by heidecjj** [comment]
You should probably be running docker as a normal user instead of as root. It looks like you might have done a `git checkout` or `git submodule update` as root at some point which messed up your permissions. If your non-root username is `user`, use `sudo chown -R user:user /home/crosshairs/deca` to make `user` the owner of `deca`. Then you should be able to run the submodule update command without errors.

Also, in case you come across times when you need `sudo`, the password for the `rose` user is `Docker!`

**Comment by Crosshairs** [comment]
![image](https://user-images.githubusercontent.com/43806118/68725713-453fe680-05fa-11ea-883e-2e367ba064be.png)
Why is the speed of the network so slow?When I clone riscv-linux.

**Comment by heidecjj** [comment]
I'm not sure. I'm glad things are at least working now though
